/-
This file is derived from lean4lean and has been modified by Argument Computer Corporation.
Modifications Copyright (c) 2026 Argument Computer Corporation.
SPDX-License-Identifier: Apache-2.0 AND (MIT OR Apache-2.0)
-/

import Lean4Lean.Verify.Environment

/-!
Front-end declaration checks that are not covered by `Lean4Lean.Tests.KernelHardening`.

The mutual-block level parameter and duplicate name checks live there, since v4.33.0-rc2
made the kernel reject both (lean4#14608).
-/

namespace Lean4Lean.Tests.Environment

open Lean

#check Lean4Lean.ElimNestedInductive.Result.canonicalPrimitive_noop
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitive_noop
#check Lean4Lean.primitiveCandidateObserversOfNestedRun
#check Lean4Lean.addDecl.inductDecl_WF_of_split_primitive_transactions_default
#check Lean4Lean.VPrimitiveInductive.canonicalDecl
#check Lean4Lean.VPrimitiveInductive.canonicalDecl_constants
#check Lean4Lean.VPrimitiveInductive.boolGeneration
#check Lean4Lean.VPrimitiveInductive.natGeneration
#check Lean4Lean.VPrimitiveInductive.canonicalGeneration
#check Lean4Lean.VPrimitiveInductive.boolGeneration_wf
#check Lean4Lean.VPrimitiveInductive.natGeneration_wf
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedValidationLparams_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedFamilySourcesClosed
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedFamilySourceStagingResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedConstructorSourcesClosed
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedFamilyConstructorsAbsent
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedFamilySourceStagingResult.endpointReadiness
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedFamilySourceStagingResult.enrich
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedFamilySourceStagingResult.enrich_of_wf
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedFamilySourceStaging
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.exists_flattenedFamilySourceStaging
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.exists_flattenedFamilySourceStaging_of_types_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.exists_flattenedEnrichedStaging
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.exists_flattenedEnrichedStaging_of_types_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.source
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.source_nparams_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.semanticInput
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.recursorShape
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.recursorShape_validationAllowPrimitive_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.recursorStaging
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.recursorSemanticInput
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.exists_flattenedEnrichedStagingResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.exists_exactRecursorStagingResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.metadataPrefix
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedEnrichedStagingResult.recursorEnv_eq_final
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.ordinaryAddInductBlockTrace
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.ordinaryTypeNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.ordinaryCtorNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.ordinaryRecNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.ordinarySafeReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedArtifact
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedArtifact.generation
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedArtifact.alignedNested
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedArtifact.alignedNested_eq
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedRestorationResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedRestorationResult.certificate
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.nestedStagedCertificate
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.selectedNestedRestoration
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.selectedNestedRestoration_run
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.selectedNestedRestoration_finalEnv_eq
#check Lean4Lean.NestedRestorationResult.name_not_primitive_of_fresh_lookup
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedRestoredMetadataPrefixRun
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedNestedRestoredMetadataPrefixRun.addInductNestedTrace
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactNestedTransactionResult
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactRecursorStagingResult.nestedTransaction
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactNestedTransactionResult.typeNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactNestedTransactionResult.ctorNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactNestedTransactionResult.recNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.FlattenedExactNestedTransactionResult.safeReplay
#check Lean4Lean.AddInductConstants.input_map_none_of_output_none
#check Lean4Lean.DeclareRestoredInfoListRun.names_not_primitive
#check Lean4Lean.AddInductive.DeclareConstructorInfoListRun.names_not_primitive
#check Lean4Lean.AddInductive.DeclareRecursorInfoListRun.names_not_primitive
#check Lean4Lean.VInductDecl.FamilyDeclarationStagingRun.raw_names_not_primitive
#check Lean4Lean.VInductDecl.ConstructorDeclarationStagingRun.raw_names_not_primitive
#check Lean4Lean.VInductDecl.RecursorDeclarationStagingRun.raw_names_not_primitive
#check Lean4Lean.EnvironmentInductiveInputClosed
#check Lean4Lean.Environment.checkInductiveInput.WF
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.inputClosed
#check Lean4Lean.TypeChecker.CandidateSemanticStage.root
#check Lean4Lean.VInductDecl.CandidateBlockFamilyTypeSourceListInput.exists_ofProduced
#check Lean4Lean.VInductDecl.CandidateBlockFamilyTypeSourceListInput.forall_names_of_declared
#check Lean4Lean.VInductDecl.CandidateConstructorSourceListInput.exists_ofProduced
#check Lean4Lean.VInductDecl.CandidateBlockSourceListInput
#check Lean4Lean.AddInductive.CandidateFamilyTypeTerminalSortList
#check Lean4Lean.AddInductive.CandidateFamilyTypeTerminalSortList.check
#check Lean4Lean.AddInductive.CandidateFamilyTypeTerminalSortList.of_check
#check Lean4Lean.AddInductive.FamilySourceClosedList
#check Lean4Lean.AddInductive.FamilySourceClosedList.check
#check Lean4Lean.AddInductive.FamilySourceClosedList.of_check
#check Lean4Lean.AddInductive.FamilySourceClosedList.check_eq_true
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.familyTypesProduced
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.familyTerminalSorts
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.constructorListsProduced
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.validationContext_allowPrimitive_all
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.validationNindicesSize_all
#check Lean4Lean.AddInductive.NormalizationCandidateExecution.familySourceStaging
#check Lean4Lean.AddInductive.ConstructorListValidationTrace.sources_closed
#check Lean4Lean.AddInductive.ConstructorBlockValidationTraces.sources_closed
#check Lean4Lean.AddInductive.ConstructorBlockValidationRun.sources_closed
#check Lean4Lean.VInductDecl.checkName_primitives_fresh
#check Lean4Lean.VInductDecl.reflectedPrimitiveNames_mem_primitives
#check Lean4Lean.AddInductive.DeclareInductiveInfoListRun.names_not_primitive
#check Lean4Lean.AddInductive.DeclareInductiveInfoListRun.names_fresh
#check Lean4Lean.AddInductive.DeclareInductiveInfoListRun.names_nodup
#check Lean4Lean.AddInductive.DeclareConstructorInfoListRun.names_fresh
#check Lean4Lean.AddInductive.DeclareConstructorInfoListRun.names_nodup
#check Lean4Lean.AddInductive.DeclareRecursorInfoListRun.names_fresh
#check Lean4Lean.AddInductive.DeclareRecursorInfoListRun.names_nodup
#check Lean4Lean.AddInductive.declaredInductiveInfos_names
#check Lean4Lean.AddInductive.declaredConstructorInfos_names
#check Lean4Lean.AddInductive.declareRecursors_infos_names
#check Lean4Lean.AddInductive.NormalizationRecursorExecution.declaredNames_nodup
#check Lean4Lean.AddInductive.NormalizationRecursorExecution.declaredNames_eq_sources
#check Lean4Lean.AddInductive.declaredConstructorInfosFor_name
#check Lean4Lean.ProjectionReady.addInductInfo_of_ctor_absent
#check Lean4Lean.StructureEtaReady.addInductInfo_of_ctor_absent
#check Lean4Lean.VInductDecl.declarationTraceConstructorAbsentReadiness
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput
#check Lean4Lean.VInductDecl.CheckedFamily.checkedFamily?
#check Lean4Lean.VInductDecl.CheckedFamilies.checkedFamilies?
#check Lean4Lean.VInductDecl.CheckedBlock.checkedBlock?
#check Lean4Lean.VInductDecl.NormalizedCheckedBlock.checkBlock?
#check Lean4Lean.VInductDecl.Normalization.checkBlock?_eq_some_iff
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.normalizedCheckedBlock
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.normalizedCheckedBlock_checkBlock?
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.blockGenerationChecked
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.blockGenerationChecked_analysis
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.blockGeneratedNames_eq_sources
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockSemanticRun.viewBlockGeneratedNames_eq_sources
#check Lean4Lean.VInductDecl.ProducedBlockRecursorShapeCandidate.semanticGeneratedNames_nodup
#check Lean4Lean.VInductDecl.ProducedBlockRecursorShapeCandidate.semanticViewGeneratedNames_nodup
#check Lean4Lean.VInductDecl.ProducedBlockRecursorShapeCandidate.semanticCheckedBlock
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput.familyInsertion
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput.stage
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput.staging
#check Lean4Lean.VEnv.stageInductiveTypes_congr_familyConstants
#check Lean4Lean.VInductDecl.CandidateBlockSourceListEnrichment
#check Lean4Lean.VInductDecl.CandidateBlockSourceListEnrichment.stage_eq
#check Lean4Lean.VInductDecl.CandidateBlockSourceListEnrichment.toRawDecl
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput.enrichedStaging
#check Lean4Lean.VInductDecl.CandidateBlockFamilyTypeSourceListInput.withConstructorsEnrichment
#check Lean4Lean.VInductDecl.CandidateBlockFamilyTypeSourceListInput.withConstructors
#check Lean4Lean.VInductDecl.CandidateBlockSourceListInput.exists_ofProduced
#check Lean4Lean.VInductDecl.CandidateBlockSourceListInput.staged
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockEnrichedStagingResult
#check Lean4Lean.VInductDecl.NormalizationCandidateBlockFamilySourceStagingInput.enrich
#check Lean4Lean.VInductDecl.ProducedBlockGenerationShapeCandidate.familySourceStaging
#check Lean4Lean.AddInductive.Context.candidateWhnfFuel
#check Lean4Lean.AddInductive.Context.candidateWhnfDepth
#check Lean4Lean.VInductDecl.BlockGenerationChecked.recursor_of_family
#check Lean4Lean.VInductDecl.BlockGenerationChecked.WF.mono
#check Lean4Lean.AddInductConstants.replay
#check Lean4Lean.AddInductBlockTrace.replay
#check Lean4Lean.AddInductBlockTrace.coherentReplay
#check Lean4Lean.AddInductNestedTrace.replay
#check Lean4Lean.AddInductNestedTrace.coherentReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.SafeReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofOrdinarySafeTrace
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofNestedSafeTrace
#check Lean4Lean.AddInductive.declaredInductiveInfos_name
#check Lean4Lean.AddInductive.declareRecursors_info_of_family
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ordinaryFamilyLookupCases
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ordinaryConstructorLookupCases
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ordinaryRecursorLookupCases
#check Lean4Lean.DeclareRestoredInfoListRun.map_wf
#check Lean4Lean.DeclareRestoredInfoListRun.map_fresh
#check Lean4Lean.DeclareRestoredInfoListRun.map_lookup_cases
#check Lean4Lean.DeclareRestoredInfoListRun.family_map_lookup_cases
#check Lean4Lean.DeclareRestoredInfoListRun.constructor_map_lookup_cases
#check Lean4Lean.DeclareRestoredInfoListRun.recursor_map_lookup_cases
#check Lean4Lean.restoredNestedInfos_family_cases
#check Lean4Lean.restoredNestedInfos_constructor_cases
#check Lean4Lean.restoredNestedInfos_recursor_of_family
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.nestedFamilyLookupCases
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.nestedConstructorLookupCases
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.nestedRecursorLookupCases
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.nestedRecursorLookupOfSourceFamily
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ordinaryStructureEtaRegistrationCoverage
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.nestedStructureEtaRegistrationCoverage
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitiveFamilyEvidence
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitiveFamilyInsertion
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitiveGenerationWF
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitiveConstructorEvidence
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.canonicalPrimitiveConstructorInsertion
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveReplay.ofInsertions
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveReplay.toTrace
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentCanonicalPrimitiveReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentCanonicalPrimitiveReplay.trace
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentCanonicalPrimitiveReplay.trace_generation
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveTransactionalVEnvsExtension
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveTransactionalVEnvsExtension.ofReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveTransactionalVEnvsExtension.ofExecution
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.CanonicalPrimitiveTransactionalVEnvsExtension.toTransactionalVEnvsExtension
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofRules
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeRules
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafePlan
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeFamilyNames
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofOrdinaryTransaction
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofNestedTransaction
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofTransaction
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeReplay
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofExactOrdinary
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofExactNested
#check Lean4Lean.AddInductive.EnvironmentInductiveExecution.flattenedValidationAllowPrimitive_eq
#check Lean4Lean.DeclarationInductiveSafe
#check Lean4Lean.addDecl.WF

/-- info: 'Lean4Lean.AddInductive.declareRecursors_info_of_family' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.declareRecursors_info_of_family

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ordinaryStructureEtaRegistrationCoverage' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ordinaryStructureEtaRegistrationCoverage

/-- info: 'Lean4Lean.restoredNestedInfos_recursor_of_family' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms Lean4Lean.restoredNestedInfos_recursor_of_family

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.nestedStructureEtaRegistrationCoverage' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.nestedStructureEtaRegistrationCoverage

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofRules' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofRules

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeRules' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeRules

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafePlan' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafePlan

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeFamilyNames' depends on axioms: [propext,
 Classical.choice,
 Quot.sound]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofSafeFamilyNames

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofOrdinaryTransaction' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofOrdinaryTransaction

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofTransaction' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.ReadinessCompletedNonprimitiveVEnvsExtension.ofTransaction

/--
info: 'Lean4Lean.AddInductBlockTrace.coherentReplay' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductBlockTrace.coherentReplay

/--
info: 'Lean4Lean.AddInductNestedTrace.coherentReplay' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductNestedTrace.coherentReplay

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofOrdinarySafeTrace' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofOrdinarySafeTrace

/--
info: 'Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofNestedSafeTrace' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 PersistentHashMap.findAux_isSome,
 PersistentHashMap.WF.find?_eq,
 PersistentHashMap.WF.toList'_insert]
-/
#guard_msgs in
#print axioms Lean4Lean.AddInductive.EnvironmentInductiveExecution.CoherentPrimitivePreservingTransactions.ofNestedSafeTrace

run_meta
  let env ← Lean.getEnv
  let some (.defnInfo natAdd) := env.toKernelEnv.find? ``Nat.add
    | throwError "Nat.add is not a definition"
  let partialNatAdd := { natAdd with safety := DefinitionSafety.partial }
  match (Lean4Lean.Environment.checkPrimitiveDef partialNatAdd).run env.toKernelEnv
      (lparams := partialNatAdd.levelParams) with
  | .ok false => pure ()
  | .ok true => throwError "a partial definition was accepted as a primitive"
  | .error _ => throwError "the partial primitive check failed unexpectedly"

end Lean4Lean.Tests.Environment
